<Project Sdk="h5.Target/25.11.62725">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>7.2</LangVersion>
        <NoWarn>$(NoWarn);NU1605</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="h5.httpclient" Version="26.3.65455" />
        <PackageReference Include="Tesserae" Version="2026.5.66312" />
        <PackageReference Include="h5" Version="26.2.64514" />
        <PackageReference Include="h5.core" Version="26.4.580" />
        <PackageReference Include="h5.Newtonsoft.Json" Version="26.3.65451" />
  </ItemGroup>
</Project>
